run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - revive
    - goimports

issues:
  exclude-rules:
    - path: bench_test\.go
      linters:
        - errcheck
  max-issues-per-linter: 10000
  max-same-issues: 10000


