run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - paralleltest
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude:
    - "var-naming"
    - "poolId should be poolID"
    - "lockId should be lockID"
    - "gaugeId should be gaugeID"
    - "nodeNameToId should be nodeNameToID"
    - "lastCommitId should be lastCommitID"
    - "latestPoolId should be latestPoolID"
    - "poolIDStr should be poolIDStr"
    - "chainId should be chainID"
    - "portId should be portID"
    - "setNextPoolId should be setNextPoolID"
    - "getNextPoolId should be getNextPoolID"
  exclude-rules:
    - path: bench_test\.go
      linters:
        - errcheck
    - path: client/docs
      linters:
        - all
    - linters:
        - staticcheck
      text: "SA1024: cutset contains duplicate characters" # proved to not provide much value, only false positives.
    - linters:
        - staticcheck
      text: "SA9004: only the first constant in this group has an explicit type" # explicitly recommended in go syntax
    - linters:
        - stylecheck
      text: "ST1003:" # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
        - revive
      text: "ST1005:" # punctuation in error messages
    - linters:
        - nolintlint
      text: "should be written without leading space as" # conflicts with gofumpt
  max-issues-per-linter: 10000
  max-same-issues: 10000
