run:
  tests: false
#   # timeout for analysis, e.g. 30s, 5m, default is 1m
#   timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - goconst
      #- gocritic # <- re enable later to catch capitalized local variables
      #    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
      #    - gosec # <- triggers too much for this round and should be re-enabled later
    - gosimple # specializes in simplifying code, subset of staticcheck binary.
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint # <- disabled because we use nolint in some places
    - paralleltest
    - promlinter
    - revive
    - staticcheck # set of rules from staticcheck, subset of staticcheck binary.
    - stylecheck # replacement of golint, subset of staticcheck binary.
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unused # looks for unused variables, subset of staticcheck binary.
    - whitespace

issues:
  exclude-rules:
    - text: increment-decrement
      linters:
        - revive
    - text: indent-error-flow
      linters:
        - revive
    - text: "ifElseChain"
      linters:
        - gocritic
    - text: "singleCaseSwitch"
      linters:
        - gocritic
    - text: "var-naming"
      linters:
        - revive
    - text: "leading space"
      linters:
        - nolintlint
    - path: bench_test\.go
      linters:
        - errcheck
    - path: client/docs
      linters:
        - all
    - linters:
        - staticcheck
      text: "SA1024: cutset contains duplicate characters" # proved to not provide much value, only false positives.
    - linters:
        - staticcheck
      text: "SA9004: only the first constant in this group has an explicit type" # explicitly recommended in go syntax
    - linters:
        - stylecheck
      text: "ST1003:" # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
      text: "ST1005:" # punctuation in error messages
  max-issues-per-linter: 10000
  max-same-issues: 10000
